# Generated by Django 3.2.8 on 2022-12-03 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shi', '0004_channelattention_hybridsn_spatialattention'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChannelAttention',
        ),
        migrations.DeleteModel(
            name='HybridSN',
        ),
        migrations.DeleteModel(
            name='SpatialAttention',
        ),
    ]
